### ISSUE TITLE
Suggestion: Have Job specific Garages that only show on that job.

### ISSUE THREAD

**Issue by TheRealDadbeard** [HumanTree92/esx_eden_garage#1]
Title. I tried my hand at it but failed. It did not spit any errors out but I couldn't build an "if" statement over 3 files...xD

Even tried to copy code thjat was there and changing variables but got nothing in the end. I have to say I can't program at all.

**Comment by HumanTree92** [comment]
Having Job Specific Garages wouldn't really do much. Since all the garages in this script are connected. Meaning if you put a vehicle in the garage at Paleto you could go to Sandy Shores & pull the car out there. As for adding job Specific garages it wouldn't work out as these garage scripts are based off of owned vehicles or rented vehicles. If what you are meaning to do is spawn vehicles & put them in the garage for other it wouldn't work as they are based off of per player.
