### ISSUE TITLE
New Plate system.

### ISSUE THREAD

**Issue by JaroSound** [HumanTree92/esx_eden_garage#2]
There is a new update to vehicleshop i think this script needs to be updated.

**Comment by puixdk** [comment]
Quick workaround. Changed the @id variable to vehicleProps.plate.

example:
if(plate == v.plate)then
				local plate = vehicleProps.plate
				local vehprop = json.encode(vehicleProps)
				MySQL.Sync.execute("UPDATE owned_vehicles SET vehicle =@vehprop WHERE plate=@id",{['@vehprop'] = vehprop, ['@id'] = plate})
				isFound = true
				break
			end

**Comment by HumanTree92** [comment]
Sorry for the late response. I have pushed this to my test team. So hopefully in the next day or so we will have it ready for launch. I am the main Dev for my community & have been really busy lately.

**Comment by HumanTree92** [comment]
@puixdk I have tried using that. However tho in the DB i removed ID since it was primary & plate is now the Primary. But so far i have gotten it to where you can pull your cars out & if its destroyed it works with the state of the vehicle. The only thing i am having a little bit of trouble with is the ability to put the vehicle back into the garage.

**Comment by HumanTree92** [comment]
This has been fixed. You can download it now. Also got property garages done as well so check that out.
